//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMap2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int j_Id { get; set; }
        public int j_Service { get; set; }
        public string j_Delivery { get; set; }
        public string j_Location { get; set; }
        public string j_Skills { get; set; }
    }
}
