//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMap2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int vh_Id { get; set; }
        public string vh_Profile { get; set; }
        public string vh_Start { get; set; }
        public string vh_End { get; set; }
        public string vh_Capacity { get; set; }
        public string vh_Skills { get; set; }
        public string vh_TimeWindow { get; set; }
    }
}
